In [1]:
import numpy as np
import torch

f = w * x <br>
For example <br>
f = 2 * x

In [ ]:
X = np.array([1,2,3,4], dtype=np.float32)
Y = np.array([2,4,6,8], dtype=np.float32)
print(X,Y)

[1. 2. 3. 4.] [2. 4. 6. 8.]


In [ ]:
w = 0 

In [ ]:
def forward(x):
  return w * x

In [ ]:
def loss(y, y_predicted):
  return ((y_predicted-y)**2).mean()


MSE = 1/N * (w*x - y)**2<br>
dj/dw = 1/N * 2x*(w*x -y) 

In [ ]:
def gradient(x,y,y_predicted):
  return np.dot(2*x,y_predicted-y).mean()

In [ ]:
# prediction before training
print(f'Prediction before training: f(5) = {forward(5):.3f}')

Prediction before training: f(5) = 0.000


In [ ]:
#Training
learning_rate = 0.01
n_iter = 15

In [ ]:
w = 0

In [ ]:
for epoch in range(n_iter):
  y_pred = forward(X)
  l = loss(Y, y_pred)
  dw = gradient(X,Y,y_pred)
  w -= learning_rate * dw
  if epoch==0:
    continue
  print(f"for epoch {epoch:.3f}: w = {w:.3f} and loss = {l}")

print(f'Prediction after training: f(5) = {forward(5):.3f}')



for epoch 1.000: w = 1.680 and loss = 4.799999237060547
for epoch 2.000: w = 1.872 and loss = 0.7680001854896545
for epoch 3.000: w = 1.949 and loss = 0.1228799968957901
for epoch 4.000: w = 1.980 and loss = 0.019660834223031998
for epoch 5.000: w = 1.992 and loss = 0.0031457357108592987
for epoch 6.000: w = 1.997 and loss = 0.0005033080233260989
for epoch 7.000: w = 1.999 and loss = 8.053186320466921e-05
for epoch 8.000: w = 1.999 and loss = 1.2884394891443662e-05
for epoch 9.000: w = 2.000 and loss = 2.0613531432900345e-06
for epoch 10.000: w = 2.000 and loss = 3.297340072094812e-07
for epoch 11.000: w = 2.000 and loss = 5.282345227897167e-08
for epoch 12.000: w = 2.000 and loss = 8.487816671731707e-09
for epoch 13.000: w = 2.000 and loss = 1.3369572116062045e-09
for epoch 14.000: w = 2.000 and loss = 2.1679014139408537e-10
Prediction after training: f(5) = 10.000


# Now Everything with PyTorch

In [ ]:
X = torch.tensor([1,2,3,4], dtype=torch.float32)
Y = torch.tensor([2,4,6,8], dtype=torch.float32)
print(X,Y)

tensor([1., 2., 3., 4.]) tensor([2., 4., 6., 8.])


In [ ]:
w = torch.tensor(0.0, dtype=torch.float32, requires_grad=True)

In [ ]:
#Training
learning_rate = 0.01
n_iter = 40

In [ ]:
for epoch in range(n_iter):
  y_pred = forward(X)
  l = loss(Y, y_pred)
  l.backward() #dl/dw

  with torch.no_grad():
    w -= learning_rate * w.grad
  
  w.grad.zero_()
  if epoch % 10 == 0:
    print(f"for epoch {epoch:.3f}: w = {w:.3f} and loss = {l}")

print(f'Prediction after training: f(5) = {forward(5):.3f}')


for epoch 0.000: w = 0.300 and loss = 30.0
for epoch 10.000: w = 1.665 and loss = 1.1627856492996216
for epoch 20.000: w = 1.934 and loss = 0.0450688973069191
for epoch 30.000: w = 1.987 and loss = 0.0017468547448515892
Prediction after training: f(5) = 9.985


#Part 2

1) Design Model (input, output size, forward pass)<br>
2) Construct loss and optimizer<br>
3) Trainging Loop<br>
      a) Forward Pass: compute prediction<br>
      b) backward Pass: Gradients<br>
      c) update weights<br>

In [6]:
import torch.nn as nn

In [ ]:
X = torch.tensor([1,2,3,4], dtype=torch.float32)
Y = torch.tensor([2,4,6,8], dtype=torch.float32)
print(X,Y)

tensor([1., 2., 3., 4.]) tensor([2., 4., 6., 8.])


In [ ]:
#Training
learning_rate = 0.01
n_iter = 100

In [ ]:
loss = nn.MSELoss()
optimizer = torch.optim.SGD([w], lr =learning_rate)

In [ ]:
w = torch.tensor(0.0, dtype=torch.float32, requires_grad=True)
w

tensor(0., requires_grad=True)

In [ ]:
for epoch in range(n_iter):
  
  # prediction
  y_pred = forward(X)
  
  #loss
  l = loss(Y, y_pred)
  
  #gradient
  l.backward()
  


  if epoch % 10 == 0:
    print(f"for epoch {epoch:.3f}: w = {w:.3f} and loss = {l}")

  #update
  optimizer.step()
  
  #zero gradients
  optimizer.zero_grad()
  
print(f'Prediction after training: f(5) = {forward(5):.3f}')

for epoch 0.000: w = 0.000 and loss = 30.0
for epoch 10.000: w = 1.606 and loss = 1.1627856492996216
for epoch 20.000: w = 1.922 and loss = 0.0450688973069191
for epoch 30.000: w = 1.985 and loss = 0.0017468547448515892
for epoch 40.000: w = 1.997 and loss = 6.770494655938819e-05
for epoch 50.000: w = 1.999 and loss = 2.6243997126584873e-06
for epoch 60.000: w = 2.000 and loss = 1.0175587306093803e-07
for epoch 70.000: w = 2.000 and loss = 3.9741685498029256e-09
for epoch 80.000: w = 2.000 and loss = 1.4670220593870908e-10
for epoch 90.000: w = 2.000 and loss = 5.076827847005916e-12
Prediction after training: f(5) = 10.000


# Creating the Model : replacing Forward Prop

In [2]:
import torch
import torch.nn as nn

In [17]:
#x & y have to be declared
X = torch.tensor([[1], [2], [3], [4]], dtype=torch.float32)   # 2D array where number of rows is the number of sample, column = feature
Y = torch.tensor([[2], [4], [6], [8]], dtype=torch.float32)
X

tensor([[1.],
        [2.],
        [3.],
        [4.]])

In [18]:
n_samples, n_features = X.shape
print(n_samples, n_features)

4 1


In [19]:
input_size = n_features
output_size = n_features

In [7]:
model = nn.Linear(input_size, output_size)

In [20]:
#because model needs a tensor
X_test = torch.tensor([5], dtype=torch.float32)

In [21]:
#item() is used for getting the exact float value
print(f'Prediction before training f(5) = {model(X_test).item():.3f}')

Prediction before training f(5) = nan


In [8]:
learning_rate = 0.5
n_iters = 200

In [13]:
#Optimizer is updated
loss = nn.MSELoss()
optimizer = torch.optim.SGD(model.parameters(), lr = learning_rate)

In [7]:
w = torch.tensor([0], dtype=torch.float32, requires_grad=True)
w

tensor([0.], requires_grad=True)

In [31]:
for epoch in range(n_iters):
  #forward pass
  y_pred = model(X)

  #loss
  l = loss(Y, y_pred)

  #gradients dl/dw
  l.backward()

  #update
  optimizer.step()

  #zero_gradient
  optimizer.zero_grad()


  if epoch % 10 == 0:
    [w,b] = model.parameters()
    print(f'epoch {epoch + 1}: w = {w[0][0].item():.3f} loss = {l:.3f}')

print(f'Prediction before training f(5) = {model(X_test).item():.3f}')




epoch 1: w = 1.878 loss = 0.022
epoch 11: w = 1.882 loss = 0.020
epoch 21: w = 1.885 loss = 0.019
epoch 31: w = 1.889 loss = 0.018
epoch 41: w = 1.892 loss = 0.017
epoch 51: w = 1.895 loss = 0.016
epoch 61: w = 1.898 loss = 0.015
epoch 71: w = 1.901 loss = 0.014
epoch 81: w = 1.904 loss = 0.013
epoch 91: w = 1.907 loss = 0.013
epoch 101: w = 1.910 loss = 0.012
epoch 111: w = 1.912 loss = 0.011
epoch 121: w = 1.915 loss = 0.010
epoch 131: w = 1.918 loss = 0.010
epoch 141: w = 1.920 loss = 0.009
epoch 151: w = 1.922 loss = 0.009
epoch 161: w = 1.925 loss = 0.008
epoch 171: w = 1.927 loss = 0.008
epoch 181: w = 1.929 loss = 0.007
epoch 191: w = 1.931 loss = 0.007
Prediction before training f(5) = 9.862


# Writing the model manually

In [22]:
X = torch.tensor([[1], [2], [3], [4]], dtype=torch.float32)   # 2D array where number of rows is the number of sample, column = feature
Y = torch.tensor([[2], [4], [6], [8]], dtype=torch.float32)
X_test = torch.tensor([5], dtype=torch.float32)
n_samples, n_features = X.shape


In [33]:
w = torch.tensor([0], dtype=torch.float32, requires_grad=True)

In [34]:
learning_rate = 0.01
n_iters = 100

In [35]:
input_size = n_features
output_size = n_features

In [36]:


class LinearRegression(nn.Module):
  def __init__(self,input_dim, output_dim):
    super(LinearRegression, self).__init__()

    #define layers
    self.lin = nn.Linear(input_dim, output_dim)

  def forward(self,x):
    return self.lin(x)


In [37]:
w = torch.tensor([0], dtype=torch.float32, requires_grad=True)
w

tensor([0.], requires_grad=True)

In [38]:
model = LinearRegression(input_size,output_size)


In [39]:
#item() is used for getting the exact float value
print(f'Prediction before training f(5) = {model(X_test).item():.3f}')

Prediction before training f(5) = 1.481


In [40]:
#Optimizer is updated
loss = nn.MSELoss()
optimizer = torch.optim.SGD(model.parameters(), lr = learning_rate)

In [41]:
for epoch in range(n_iters):
  #forward pass
  y_pred = model(X)

  #loss
  l = loss(Y, y_pred)

  #gradients dl/dw
  l.backward()

  #update
  optimizer.step()

  #zero_gradient
  optimizer.zero_grad()


  if epoch % 10 == 0:
    [w,b] = model.parameters()
    print(f'epoch {epoch + 1}: w = {w[0][0].item():.3f} loss = {l:.3f}')

print(f'Prediction after training f(5) = {model(X_test).item():.3f}')




epoch 1: w = 0.627 loss = 22.967
epoch 11: w = 1.726 loss = 0.600
epoch 21: w = 1.904 loss = 0.021
epoch 31: w = 1.935 loss = 0.006
epoch 41: w = 1.941 loss = 0.005
epoch 51: w = 1.943 loss = 0.005
epoch 61: w = 1.945 loss = 0.004
epoch 71: w = 1.947 loss = 0.004
epoch 81: w = 1.948 loss = 0.004
epoch 91: w = 1.950 loss = 0.004
Prediction after training f(5) = 9.899
